import java.util.*;
public class exception {
    public static void main(String[] args) {
       Scanner sc = new Scanner(System.in);
      /* int divider = sc.nextInt();
       int divisor = sc.nextInt();
       try{
       int result = divider/divisor;
       System.out.println("result : "+ result); 
    }
    catch(ArithmeticException A){
        System.out.println(A.getMessage());
    } */
    
//    int arr[] = new int[5];
//    try{
//        arr[5] = 5/4;

//     }


//    catch(ArithmeticException | ArrayIndexOutOfBoundsException e){
//     System.out.println(e.getMessage());
//    }

//System.out.println(arr[4]);
   //    catch(ArithmeticException e){
//     System.out.println(e.getMessage());
//    }

 try{
     checkAge(16);
 }
 catch(Exception e){
     System.out.println(e.getMessage());
     }


public static void checkAge(int age){


}
}
}
